name: airbyte_utils
version: '1.0'
config-version: 2
profile: normalize
model-paths:
- models
docs-paths:
- docs
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
target-path: ../build
log-path: ../logs
packages-install-path: /dbt
clean-targets:
- build
- dbt_modules
quoting:
  database: true
  schema: false
  identifier: true
models:
  airbyte_utils:
    +materialized: table
    generated:
      airbyte_ctes:
        +tags: airbyte_internal_cte
        +materialized: ephemeral
      airbyte_incremental:
        +tags: incremental_tables
        +materialized: incremental
        +on_schema_change: sync_all_columns
      airbyte_tables:
        +tags: normalized_tables
        +materialized: table
      airbyte_views:
        +tags: airbyte_internal_views
        +materialized: view
dispatch:
- macro_namespace: dbt_utils
  search_order:
  - airbyte_utils
  - dbt_utils
vars:
  json_column: _airbyte_data
  models_to_source:
    products_ab1: public._airbyte_raw_products
    products_ab2: public._airbyte_raw_products
    products_stg: public._airbyte_raw_products
    products_scd: public._airbyte_raw_products
    products: public._airbyte_raw_products
    products__links_ab1: public._airbyte_raw_products
    products__links_ab2: public._airbyte_raw_products
    products__links_ab3: public._airbyte_raw_products
    products__links: public._airbyte_raw_products
    products_variants_ab1: public._airbyte_raw_products
    products_variants_ab2: public._airbyte_raw_products
    products_variants_ab3: public._airbyte_raw_products
    products_variants: public._airbyte_raw_products
    products_meta_data_ab1: public._airbyte_raw_products
    products_meta_data_ab2: public._airbyte_raw_products
    products_meta_data_ab3: public._airbyte_raw_products
    products_meta_data: public._airbyte_raw_products
    products__links_self_ab1: public._airbyte_raw_products
    products__links_self_ab2: public._airbyte_raw_products
    products__links_self_ab3: public._airbyte_raw_products
    products__links_self: public._airbyte_raw_products
    products__links_collection_ab1: public._airbyte_raw_products
    products__links_collection_ab2: public._airbyte_raw_products
    products__links_collection_ab3: public._airbyte_raw_products
    products__links_collection: public._airbyte_raw_products
